# Generated by Django 3.2.25 on 2024-03-25 22:50

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('js_blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='title_ini',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Titulo de inicio'),
        ),
    ]
