# Generated by Django 3.2.25 on 2024-03-25 23:46

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('js_blog_app', '0002_blogindexpage_title_ini'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='subtitle_ini',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Frase de inicio'),
        ),
    ]
